<?php

$methodCode = $block->escapeHtml($block->getMethodCode());
?>
<fieldset class="fieldset items <?= /* @noEscape */ $methodCode ?>" id="payment_form_<?= /* @noEscape */ $methodCode ?>" style="display: none">
    <div class="field number required">
        <label for="assistant_id" class="label"><span><?= $block->escapeHtml(__('Assistant ID')) ?></span></label>
        <div class="control">
            <input type="checkbox" id="coin" name="payment[additional_data][coin]" title="<?= $block->escapeHtml(__('Coin for payment')) ?>"
                   class="input-text required-entry"/>
        </div>
    </div>
</fieldset>
